### ISSUE TITLE
Exact setup for installation

### ISSUE THREAD

**Issue by gpogorzelski** [BerkeleyAutomation/dex-net#63]
Hi, I have been trying to isntall dex-net in order to generate a dataset for my own gripper and camera settings but I keep on running into a number of dependency issues. Can you please provide the exact versions of dependencies that you used when testing on Ubuntu 16.04 LTS? Thanks

**Comment by Greg8978** [comment]
Hi!
Here is what I used to compile on 16.04

`pip install --user numpy==1.16 scipy==0.17.0 scikit-learn==0.20 scikit-image==0.14.1 opencv-python==4.2.0.32 pyassimp tensorflow tensorflow-gpu h5py==2.7 mayavi matplotlib==2.2.0 catkin_pkg multiprocess dill cvxopt ipython==5.8 pillow==4.0.0 pyhull setproctitle trimesh pywavelets==0.4.0 networkx==1.7 mock==2.0.0 apptools==4.5.0 envisage==4.5.1 pyface==5.1.0 traits==5.1.1 kiwisolver==1.0.1 cppy==1.0.2 docutils==0.16 decorator==4.4.2 setuptools==18.5 traitlets==4.2 fsspec==0.4.0 markdown==2.6.8 pygments==2.5.2`

cheers

**Comment by gpogorzelski** [comment]
Hi Gregorie,
Thanks alot! Have a great day!

Regards,
Grzegorz

**Comment by aprath1** [comment]
Hi @Greg8978 ,

Thank you for sharing the pip compilation package versions. Could you please let me know the **python version** you used and also would like to know whether you used a virtual environment/WSL/direct installation of Ubuntu 16.04 for compiling.

I am having some trouble with the compilation mainly because of the apt dependencies mentioned in install.sh of dexnet. There are compilation error for Boost.Numpy due to these apt packages. The cmakelist is searching for numpy in the system python and not in my virtual environment and error output is cannot find Numpy.

**Comment by Greg8978** [comment]
Hi there!
I found out this configuration by trying different versions on virtual machine with ubuntu 16.04 and python2.7
I actually successfully did the installation but still had troubles with the test/validation.

We ended up installing only gqcnn on ubuntu 20.04 with python 3.7 (with the original pip file, just add --user after pip install).

We had to  revert perception package as the latest version is no longer compatible (intrinsicCamera was removed).
I also did minor change in code using tensorflow to fix an error of data type.

I hope this will help somehow

**Comment by Greg8978** [comment]
I would actually advice anyone who wants to use Dex-Net / GQ-CNN to read this first:

Silvia Sapora (Juin 2019)
https://www.imperial.ac.uk/media/imperial-college/faculty-of-engineering/computing/public/1819-ug-projects/SaporaS-Grasp-Quality-Deep-Neural-Networks-for-Robotic-Object-Grasping.pdf

**Comment by aprath1** [comment]
> I would actually advice anyone who wants to use Dex-Net / GQ-CNN to read this first:
> 
> Silvia Sapora (Juin 2019)
> https://www.imperial.ac.uk/media/imperial-college/faculty-of-engineering/computing/public/1819-ug-projects/SaporaS-Grasp-Quality-Deep-Neural-Networks-for-Robotic-Object-Grasping.pdf

Thank you so much! I will work on this and try to get the dexnet& gqcnn working. 
Wish you a nice day.
